name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # No external deps in this repo; add here if needed later
      - name: Run tests
        run: |
          python -m py_compile game.py decision_engine.py combat_engine.py event_resolver.py survivor.py zombies.py || true
          python -m unittest discover -v
